# Generated by Django 4.0.4 on 2022-05-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=200)),
                ('pro_des', models.CharField(max_length=2000)),
                ('photo', models.CharField(max_length=500)),
                ('time_stamp', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('current_bid', models.FloatField()),
                ('likes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('condition', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.category')),
            ],
        ),
    ]
